"""improved type model

Revision ID: 0d3ca97541a9
Revises: 66eb6e58ae7b
Create Date: 2026-01-03 13:12:11.676237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d3ca97541a9'
down_revision: Union[str, None] = '66eb6e58ae7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'status',
               existing_type=postgresql.ENUM('awaiting_payment', 'finalized', 'cancelled', name='matchstatus'),
               type_=sa.Enum('AWAITING_PAYMENT', 'FINALIZED', 'CANCELLED', name='matchstatus', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('match', 'status',
               existing_type=sa.Enum('AWAITING_PAYMENT', 'FINALIZED', 'CANCELLED', name='matchstatus', native_enum=False),
               type_=postgresql.ENUM('awaiting_payment', 'finalized', 'cancelled', name='matchstatus'),
               existing_nullable=False)
    # ### end Alembic commands ###
