"""first  migration

Revision ID: 30c50b4b046f
Revises: 
Create Date: 2025-12-04 12:32:50.369440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c50b4b046f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_type',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type_name', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('match_status',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_name')
    )
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('NANNY', 'FAMILY', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('family_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('household_location', sa.String(length=255), nullable=True),
    sa.Column('household_details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('nanny_profile',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('years_experience', sa.Integer(), nullable=True),
    sa.Column('skills', sa.Text(), nullable=True),
    sa.Column('preferred_location', sa.String(length=255), nullable=True),
    sa.Column('availability', sa.String(length=255), nullable=True),
    sa.Column('vetting_status', sa.String(length=50), nullable=True),
    sa.Column('profile_photo_url', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_post',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('childcare_needs', sa.Text(), nullable=True),
    sa.Column('hours', sa.String(length=100), nullable=True),
    sa.Column('duties', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('required_experience', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vetting_document',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nanny_id', sa.UUID(), nullable=False),
    sa.Column('doc_type_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(length=1024), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doc_type_id'], ['document_type.id'], ),
    sa.ForeignKeyConstraint(['nanny_id'], ['nanny_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('application',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('nanny_id', sa.UUID(), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nanny_id'], ['nanny_profile.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('selected_nanny_id', sa.UUID(), nullable=False),
    sa.Column('status_id', sa.UUID(), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job_post.id'], ),
    sa.ForeignKeyConstraint(['selected_nanny_id'], ['nanny_profile.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['match_status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    op.create_table('contract',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('contract_text', sa.Text(), nullable=True),
    sa.Column('generation_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_id')
    )
    op.create_table('payment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mpesa_transaction_code', sa.String(length=255), nullable=True),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mpesa_transaction_code')
    )
    op.create_table('contract_acceptance',
    sa.Column('contract_id', sa.UUID(), nullable=False),
    sa.Column('family_accepted', sa.Boolean(), nullable=True),
    sa.Column('nanny_accepted', sa.Boolean(), nullable=True),
    sa.Column('family_acceptance_date', sa.DateTime(), nullable=True),
    sa.Column('nanny_acceptance_date', sa.DateTime(), nullable=True),
    sa.Column('acting_user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['acting_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['contract_id'], ['contract.id'], ),
    sa.PrimaryKeyConstraint('contract_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_acceptance')
    op.drop_table('payment')
    op.drop_table('contract')
    op.drop_table('match')
    op.drop_table('application')
    op.drop_table('vetting_document')
    op.drop_table('job_post')
    op.drop_table('nanny_profile')
    op.drop_table('family_profile')
    op.drop_table('user')
    op.drop_table('match_status')
    op.drop_table('document_type')
    # ### end Alembic commands ###
