"""implemented all the relationships using foreign keys

Revision ID: 3bc6639530b1
Revises: 768ec74367a1
Create Date: 2025-11-28 17:06:23.048228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bc6639530b1'
down_revision: Union[str, None] = '768ec74367a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
