"""add foreign key for payments

Revision ID: 4da45a63db53
Revises: 7198e37df3dd
Create Date: 2026-04-03 22:56:47.787399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4da45a63db53'
down_revision: Union[str, None] = '7198e37df3dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('payment_match_id_fkey'), 'payment', type_='foreignkey')
    op.drop_column('payment', 'payment_date')
    op.drop_column('payment', 'match_id')
    op.drop_constraint(op.f('payment_match_link_payment_id_fkey'), 'payment_match_link', type_='foreignkey')
    op.drop_constraint(op.f('payment_match_link_match_id_fkey'), 'payment_match_link', type_='foreignkey')
    op.create_foreign_key(None, 'payment_match_link', 'match', ['match_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payment_match_link', 'payment', ['payment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment_match_link', type_='foreignkey')
    op.drop_constraint(None, 'payment_match_link', type_='foreignkey')
    op.create_foreign_key(op.f('payment_match_link_match_id_fkey'), 'payment_match_link', 'match', ['match_id'], ['id'])
    op.create_foreign_key(op.f('payment_match_link_payment_id_fkey'), 'payment_match_link', 'payment', ['payment_id'], ['id'])
    op.add_column('payment', sa.Column('match_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('payment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('payment_match_id_fkey'), 'payment', 'match', ['match_id'], ['id'])
    # ### end Alembic commands ###
