"""implemented all the relationships using foreign keys

Revision ID: 5e2e965374b5
Revises: 9a5585bbffa5
Create Date: 2025-11-28 18:21:48.242848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2e965374b5'
down_revision: Union[str, None] = '9a5585bbffa5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
