"""upgrade without match_status table

Revision ID: 66eb6e58ae7b
Revises: 961f31b5ab0f
Create Date: 2026-01-03 12:35:32.563881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66eb6e58ae7b'
down_revision: Union[str, None] = '961f31b5ab0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('match_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_status',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('match_status_pkey')),
    sa.UniqueConstraint('status_name', name=op.f('match_status_status_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
