"""updated the schema to include payment status enum

Revision ID: 677bc3cffae4
Revises: 0d3ca97541a9
Create Date: 2026-01-28 10:43:47.683725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '677bc3cffae4'
down_revision: Union[str, None] = '0d3ca97541a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'payment_status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='paymentstatus', native_enum=False),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payment', 'payment_status',
               existing_type=sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='paymentstatus', native_enum=False),
               type_=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
