"""updated the payment schema

Revision ID: 7dfafd3c7845
Revises: 677bc3cffae4
Create Date: 2026-01-28 11:04:01.116010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7dfafd3c7845'
down_revision: Union[str, None] = '677bc3cffae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('checkout_request_id', sa.String(length=255), nullable=True))
    op.add_column('payment', sa.Column('merchant_request_id', sa.String(length=255), nullable=True))
    op.add_column('payment', sa.Column('result_code', sa.Integer(), nullable=True))
    op.add_column('payment', sa.Column('result_description', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'payment', ['checkout_request_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='unique')
    op.drop_column('payment', 'result_description')
    op.drop_column('payment', 'result_code')
    op.drop_column('payment', 'merchant_request_id')
    op.drop_column('payment', 'checkout_request_id')
    # ### end Alembic commands ###
