"""updated the schema added created_at and updated_at

Revision ID: 804b92c3bb10
Revises: 7dfafd3c7845
Create Date: 2026-01-28 11:14:25.050001

"""
from typing import Sequence, Union
from sqlalchemy.sql import func
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804b92c3bb10'
down_revision: Union[str, None] = '7dfafd3c7845'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=func.now() ))
    op.add_column('application', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=func.now() ))
    op.add_column('contract', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=func.now() ))
    op.add_column('contract', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=func.now() ))
    op.add_column('family_profile', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=func.now() ))
    op.add_column('family_profile', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=func.now() ))
    op.add_column('job_post', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=func.now() ))
    op.add_column('match', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=func.now() ))
    op.add_column('match', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=func.now() ))
    op.add_column('nanny_profile', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=func.now() ))
    op.add_column('nanny_profile', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=func.now() ))
    op.add_column('payment', sa.Column('transaction_date', sa.DateTime(), nullable=True))
    op.add_column('payment', sa.Column('phone_number', sa.String(length=15), nullable=False))
    op.add_column('payment', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=func.now() ))
    op.add_column('payment', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=func.now() ))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payment', 'updated_at')
    op.drop_column('payment', 'created_at')
    op.drop_column('payment', 'phone_number')
    op.drop_column('payment', 'transaction_date')
    op.drop_column('nanny_profile', 'updated_at')
    op.drop_column('nanny_profile', 'created_at')
    op.drop_column('match', 'updated_at')
    op.drop_column('match', 'created_at')
    op.drop_column('job_post', 'updated_at')
    op.drop_column('family_profile', 'updated_at')
    op.drop_column('family_profile', 'created_at')
    op.drop_column('contract', 'updated_at')
    op.drop_column('contract', 'created_at')
    op.drop_column('application', 'updated_at')
    op.drop_column('application', 'created_at')
    # ### end Alembic commands ###
