"""add foreign key for payments

Revision ID: 935331eeb2b4
Revises: 9726143590e4
Create Date: 2026-04-03 21:46:21.581286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '935331eeb2b4'
down_revision: Union[str, None] = '9726143590e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('match_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'payment', 'match', ['match_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_column('payment', 'match_id')
    # ### end Alembic commands ###
