"""merged the match_status with the match table

Revision ID: 961f31b5ab0f
Revises: f7c49b8911fb
Create Date: 2025-12-30 12:18:59.746836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '961f31b5ab0f'
down_revision: Union[str, None] = 'f7c49b8911fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    match_status_enum = sa.Enum(
        'awaiting_payment', 
        'finalized', 
        'cancelled', 
        name='matchstatus'
    )

    match_status_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('match', sa.Column('status', sa.Enum('AWAITING_PAYMENT', 'FINALIZED', 'CANCELLED', name='matchstatus'), nullable=False))
    op.drop_constraint(op.f('match_status_id_fkey'), 'match', type_='foreignkey')
    op.drop_column('match', 'status_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('status_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('match_status_id_fkey'), 'match', 'match_status', ['status_id'], ['id'])
    op.drop_column('match', 'status')
    # ### end Alembic commands ###
