"""updated the payment model to handle batch matches

Revision ID: 9726143590e4
Revises: 9cbbf965810c
Create Date: 2026-04-03 21:08:49.604297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9726143590e4'
down_revision: Union[str, None] = '9cbbf965810c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_match_link',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('match_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.PrimaryKeyConstraint('payment_id', 'match_id')
    )
    op.add_column('payment', sa.Column('result_desc', sa.String(length=255), nullable=True))
    op.alter_column('payment', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=False)
    op.alter_column('payment', 'phone_number',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('payment', 'mpesa_transaction_code',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('payment', 'payment_status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_constraint(op.f('payment_checkout_request_id_key'), 'payment', type_='unique')
    op.drop_constraint(op.f('payment_mpesa_transaction_code_key'), 'payment', type_='unique')
    op.drop_constraint(op.f('uix_match_user'), 'payment', type_='unique')
    op.create_index(op.f('ix_payment_checkout_request_id'), 'payment', ['checkout_request_id'], unique=False)
    op.drop_constraint(op.f('payment_match_id_fkey'), 'payment', type_='foreignkey')
    op.drop_column('payment', 'result_description')
    op.drop_column('payment', 'match_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('match_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('result_description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('payment_match_id_fkey'), 'payment', 'match', ['match_id'], ['id'])
    op.drop_index(op.f('ix_payment_checkout_request_id'), table_name='payment')
    op.create_unique_constraint(op.f('uix_match_user'), 'payment', ['match_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('payment_mpesa_transaction_code_key'), 'payment', ['mpesa_transaction_code'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('payment_checkout_request_id_key'), 'payment', ['checkout_request_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('payment', 'payment_status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('payment', 'mpesa_transaction_code',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('payment', 'phone_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=15),
               existing_nullable=False)
    op.alter_column('payment', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=False)
    op.drop_column('payment', 'result_desc')
    op.drop_table('payment_match_link')
    # ### end Alembic commands ###
