"""implemented all the relationships using foreign keys

Revision ID: 9a5585bbffa5
Revises: d28b7d72e52d
Create Date: 2025-11-28 18:15:55.230856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a5585bbffa5'
down_revision: Union[str, None] = 'd28b7d72e52d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
