"""updated contract acceptance table

Revision ID: 9cbbf965810c
Revises: c995309824c2
Create Date: 2026-03-29 01:49:09.168566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cbbf965810c'
down_revision: Union[str, None] = 'c995309824c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('application')
    op.drop_table('job_post')
    op.alter_column('contract_acceptance', 'acting_user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('match', 'match_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(op.f('match_family_id_fkey'), 'match', type_='foreignkey')
    op.create_foreign_key(None, 'match', 'family_profile', ['family_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.create_foreign_key(op.f('match_family_id_fkey'), 'match', 'family_profile', ['family_id'], ['id'])
    op.alter_column('match', 'match_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('contract_acceptance', 'acting_user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('job_post',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('family_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('duties', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('required_experience', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('care_needs', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('availability', postgresql.ENUM('FULL_TIME', 'PART_TIME', 'WEEKENDS', 'EVENINGS', name='nannyavailability'), autoincrement=False, nullable=False),
    sa.Column('salary', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('OPEN', 'FILLED', name='jobstatus'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['family_id'], ['family_profile.id'], name='job_post_family_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='job_post_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('application',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('nanny_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('applied_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'REVIEWING', 'INTERVIEW', 'ACCEPTED', 'REJECTED', name='applicationstatus'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_post.id'], name=op.f('application_job_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['nanny_id'], ['nanny_profile.id'], name=op.f('application_nanny_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('application_pkey'))
    )
    # ### end Alembic commands ###
