"""added family_id in match schema

Revision ID: 9eceac80f280
Revises: 4f8211469040
Create Date: 2026-01-28 13:16:31.918813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eceac80f280'
down_revision: Union[str, None] = '4f8211469040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('family_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'match', 'family_profile', ['family_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_column('match', 'family_id')
    # ### end Alembic commands ###
