"""implemented all the relationships using foreign keys

Revision ID: a3d34f6b898e
Revises: e6a2637cb7f3
Create Date: 2025-11-28 16:54:47.530266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3d34f6b898e'
down_revision: Union[str, None] = 'e6a2637cb7f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'application', 'job_post', ['job_id'], ['id'])
    op.create_foreign_key(None, 'application', 'nanny_profile', ['nanny_id'], ['id'])
    op.create_foreign_key(None, 'contract', 'match', ['match_id'], ['id'])
    op.create_foreign_key(None, 'contract_acceptance', 'contract', ['contract_id'], ['id'])
    op.create_foreign_key(None, 'family_profile', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'job_post', 'family_profile', ['family_id'], ['id'])
    op.create_foreign_key(None, 'match', 'nanny_profile', ['selected_nanny_id'], ['id'])
    op.create_foreign_key(None, 'match', 'job_post', ['job_id'], ['id'])
    op.create_foreign_key(None, 'nanny_profile', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'payment', 'match', ['match_id'], ['id'])
    op.create_foreign_key(None, 'vetting_document', 'nanny_profile', ['nanny_id'], ['id'])
    op.create_foreign_key(None, 'vetting_document', 'document_type', ['doc_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vetting_document', type_='foreignkey')
    op.drop_constraint(None, 'vetting_document', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'payment', type_='foreignkey')
    op.drop_constraint(None, 'nanny_profile', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'job_post', type_='foreignkey')
    op.drop_constraint(None, 'family_profile', type_='foreignkey')
    op.drop_constraint(None, 'contract_acceptance', type_='foreignkey')
    op.drop_constraint(None, 'contract', type_='foreignkey')
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_constraint(None, 'application', type_='foreignkey')
    # ### end Alembic commands ###
