"""implemented all the relationships using foreign keys

Revision ID: b51571bd49fa
Revises: 3bc6639530b1
Create Date: 2025-11-28 17:13:23.374531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51571bd49fa'
down_revision: Union[str, None] = '3bc6639530b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
