"""implemented all the relationships using foreign keys

Revision ID: befd17c30a28
Revises: 5e2e965374b5
Create Date: 2025-11-28 18:24:55.418454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'befd17c30a28'
down_revision: Union[str, None] = '5e2e965374b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'match', 'match_status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'match', type_='foreignkey')
    # ### end Alembic commands ###
