"""added a unique constraint in payments for user_id and match_id

Revision ID: c37fc7819f89
Revises: 9eceac80f280
Create Date: 2026-01-28 15:18:58.837845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c37fc7819f89'
down_revision: Union[str, None] = '9eceac80f280'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uix_match_user', 'payment', ['match_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_match_user', 'payment', type_='unique')
    # ### end Alembic commands ###
