"""changed the jobpost model

Revision ID: c66b22aa8c6e
Revises: 60cb73ce5e1a
Create Date: 2025-12-17 21:41:34.562815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c66b22aa8c6e'
down_revision: Union[str, None] = '60cb73ce5e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_post', sa.Column('care_needs', sa.Text(), nullable=True))
    op.add_column('job_post', sa.Column('availability', sa.Enum('FULL_TIME', 'PART_TIME', 'WEEKENDS', 'EVENINGS', name='nannyavailability'), nullable=False))
    op.drop_column('job_post', 'hours')
    op.drop_column('job_post', 'childcare_needs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_post', sa.Column('childcare_needs', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('job_post', sa.Column('hours', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('job_post', 'availability')
    op.drop_column('job_post', 'care_needs')
    # ### end Alembic commands ###
