"""updated schema to implement connection based

Revision ID: c995309824c2
Revises: 7914235fe9a6
Create Date: 2026-03-27 11:13:22.370886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c995309824c2'
down_revision: Union[str, None] = '7914235fe9a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # 1. Add column safely
    op.execute("ALTER TABLE match ADD COLUMN IF NOT EXISTS nanny_id UUID")
    
    # 2. Data Migration: Copy IDs
    op.execute("UPDATE match SET nanny_id = selected_nanny_id WHERE nanny_id IS NULL")
    
    # 3. Make it NOT NULL
    op.alter_column('match', 'nanny_id', nullable=False)

    # --- NEW: Deduplication Logic ---
    # Delete older duplicate matches, keeping only the most recently created one
    op.execute("""
        DELETE FROM match a USING match b
        WHERE a.id < b.id
        AND a.family_id = b.family_id
        AND a.nanny_id = b.nanny_id
    """)
    # --------------------------------

    # 4. Now create the Unique Constraint safely
    try:
        op.drop_constraint('match_job_id_key', 'match', type_='unique')
    except Exception:
        pass
        
    op.create_unique_constraint('uix_family_nanny_match', 'match', ['family_id', 'nanny_id'])
    
    # 5. Drop old Foreign Keys
    for fk in ['match_selected_nanny_id_fkey', 'match_job_id_fkey']:
        try:
            op.drop_constraint(fk, 'match', type_='foreignkey')
        except Exception:
            continue

    # 6. Create new Foreign Keys
    op.create_foreign_key('match_nanny_id_fkey', 'match', 'nanny_profile', ['nanny_id'], ['id'], ondelete='CASCADE')
    
    # 7. Cleanup old columns
    op.drop_column('match', 'job_id')
    op.drop_column('match', 'selected_nanny_id')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('selected_nanny_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('match', sa.Column('job_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.create_foreign_key(op.f('match_job_id_fkey'), 'match', 'job_post', ['job_id'], ['id'])
    op.create_foreign_key(op.f('match_family_id_fkey'), 'match', 'family_profile', ['family_id'], ['id'])
    op.create_foreign_key(op.f('match_selected_nanny_id_fkey'), 'match', 'nanny_profile', ['selected_nanny_id'], ['id'])
    op.drop_constraint('uix_family_nanny_match', 'match', type_='unique')
    op.create_unique_constraint(op.f('match_job_id_key'), 'match', ['job_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('match', 'match_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_column('match', 'nanny_id')
    # ### end Alembic commands ###
