"""implemented all the relationships using foreign keys

Revision ID: d28b7d72e52d
Revises: b51571bd49fa
Create Date: 2025-11-28 17:29:01.172466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28b7d72e52d'
down_revision: Union[str, None] = 'b51571bd49fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('application_nanny_id_fkey'), 'application', type_='foreignkey')
    op.drop_constraint(op.f('application_job_id_fkey'), 'application', type_='foreignkey')
    op.create_foreign_key(None, 'application', 'job_post', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'application', 'nanny_profile', ['nanny_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.create_foreign_key(op.f('application_job_id_fkey'), 'application', 'job_post', ['job_id'], ['id'])
    op.create_foreign_key(op.f('application_nanny_id_fkey'), 'application', 'nanny_profile', ['nanny_id'], ['id'])
    # ### end Alembic commands ###
