"""added name in the family and nanny profile schema

Revision ID: de05e5c08556
Revises: e44ccbbdb441
Create Date: 2026-02-06 17:35:01.576205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de05e5c08556'
down_revision: Union[str, None] = 'e44ccbbdb441'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_profile', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('nanny_profile', sa.Column('name', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nanny_profile', 'name')
    op.drop_column('family_profile', 'name')
    # ### end Alembic commands ###
