"""updated the job_post schema

Revision ID: f7c49b8911fb
Revises: c66b22aa8c6e
Create Date: 2025-12-22 13:41:54.978825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7c49b8911fb'
down_revision: Union[str, None] = 'c66b22aa8c6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    job_status_enum = sa.Enum('OPEN', 'FILLED', name='jobstatus')
    job_status_enum.create(op.get_bind(), checkfirst=True)
    
    op.add_column('job_post', sa.Column('salary', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('job_post', sa.Column('status', sa.Enum('OPEN', 'FILLED', name='jobstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_post', 'status')
    op.drop_column('job_post', 'salary')
    # ### end Alembic commands ###
